services:
  nginx:
    image: "nginx:latest"
    ports:
      - "8006:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/laravel    
  php:
    build: 
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/laravel    
  mysql:
    image: mysql:9.1
    ports:
      - "3318:3306"
    env_file:
      - ./env/mysql.env  
  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes: 
      - ./:/var/www/laravel 